### ISSUE TITLE
python3 support

### ISSUE THREAD

**Issue by vuleetu** [reconquest/vim-pythonx#12]
Any plan for python3 support?

**Comment by kovetskiy** [comment]
@vuleetu btw, why do you need it? From my experience, python3 is much slower than python2 in Vim.

**Comment by kleinjm** [comment]
See https://robertbasic.com/blog/force-python-version-in-vim/ for a how to set your python version

**Comment by Corey-Keller** [comment]
TL;DR change all calls to 'py' into 'pyx' in  "plugin/pythonx.vim" and "pythonx/px/autocommands.py" and python 3 seems to work. 

The following commit from @ColinKennedy seems to be sufficient for everything to work with just python 3 (at least it does in my limited usage)
https://github.com/ColinKennedy/vim-pythonx/commit/4a9adcf4aacb929757b58cf62054d1a42134708f

**Comment by kovetskiy** [comment]
Makes sense #d8b45a48e35fecc819441fbf02bb0beb574a3096
