### ISSUE TITLE
error on gvim startup because c:/tmp/pythonx.log doesn't exist 

### ISSUE THREAD

**Issue by alancanniff** [reconquest/vim-pythonx#13]
I'm using gvim 8.1 on windows 10
on start up this package looks for c:/tmp/pythonx.log which doesn't exists on my system. 
This raises an error dialog and stops the package from working. If I create the file manually the error does not occur and the package works as exected.  
I've attached a file with the output of :messages from the errored condition.
[pythonx_message.txt](https://github.com/reconquest/vim-pythonx/files/2526833/pythonx_message.txt)

**Comment by kovetskiy** [comment]
@alancanniff wow, that's very-very unexpected that someone uses and moreover, on Windows :+1:

I will take a look at it next week (vacation), but if you have any chance to fix it by your own, I'd be glad to merge PR.

**Comment by alancanniff** [comment]
Your library is used in some of the Ultisnips examples - which I’ve been playing around with. I’m not a programmer by trade some I’m not sure you really want me poking around in your code! (...but if I get time next week I’ll have a look) - in the mean time enjoy you vacation.

**Comment by kovetskiy** [comment]
Hi, I've just removed usage of this file, please take a look that it works for your windows setup.
